spring:
  application:
    name: insurance-policies
  profiles:
    active: local
  config:
    import: "optional:configserver:http://insurance-configserver:8888"

eureka:
  client:
    service-url:
      defaultZone: http://insurance-eureka:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh
